---
# tasks file for dep-java7

- name: "Install Java 1.7.0"
  yum: name=java-1.7.0-openjdk state=present
  when: action|lower == 'install'

- name: "Remove Java 1.7.0"
  yum: name=java-1.7.0-openjdk state=absent
  when: action|lower == 'uninstall'
