  - name: "Update Hostname"
    lineinfile:
      dest: /etc/sysconfig/network
      regexp: '^HOSTNAME='
      line: "HOSTNAME={{ ansible_hostname }}.localdomain"

  - name: "Update /etc/hosts"
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      backup: yes
      line: "127.0.0.1	localhost localhost.domain {{ ansible_hostname }} {{ ansible_hostname }}.localdomain"
