---
# tasks file for task-hostname

- name: "Include OS Specific Playbook"
  include_tasks: "{{ item }}"
  with_first_found:
  - "{{ ansible_distribution | lower }}.yml"
  - "{{ ansible_os_family | lower }}.yml"
